### ISSUE TITLE
Not able to access gym environment

### ISSUE THREAD

**Issue by efotopoulou** [ymzhang01/access-control#1]
Thanks for your example on the access control problem as a gym environment.  
I have successfully installed the environment, however i can not load it.
Any help would be very useful.

```
>>> env = gym.make('access_control:AccessControl-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eleni/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/home/eleni/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "/home/eleni/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 58, in make
    cls = load(self.entry_point)
  File "/home/eleni/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "access_control/envs/__init__.py", line 1, in <module>
    from access_control.envs.access_control import AccessControlEnv
ImportError: No module named envs.access_control
```

**Comment by efotopoulou** [comment]
it just worked fine with python 3 .
It seems to have some incompatibility with python 2.
Thanks again for your example.
